spring.config.import=optional:file:.env[.properties]
spring.application.name=echoes-server

server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=meu-cert

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.socketfactory.port=465
spring.mail.properties.mail.smtp.socketfactory.class=javax.net.ssl.SSLSocketFactory

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.password=
spring.data.redis.port=6379

api.smtp.token=${API_KEY}
api.security.token.secret=${JWT_SECRET}

twofactor.provider=${TWO_FACTOR_PROVIDER}
